### ISSUE TITLE
[To do] Google Fitness API

### ISSUE THREAD

**Issue by Lee-Soyeon** [DahamChoi/SilverWalk#2]
## Description

* Date : 3/11 ~ 3/13

## Progress

- [x] Setup

## Platform overview 
![Platform overview](https://developers.google.com/fit/images/arch-gen.png)

## Reference

[Google fit API 사용하기 위한 설정](https://m.blog.naver.com/PostView.nhn?blogId=venusyu&logNo=220514362242&proxyReferer=https:%2F%2Fwww.google.com%2F)
[Getting Started on Android](https://developers.google.com/fit/android/get-started)
[코틀린(Kotlin) 안드로이드 멀티 퍼미션(권한, multi permission) 체크 및 요청 처리하기](https://m.blog.naver.com/PostView.nhn?blogId=chandong83&logNo=221616557088&proxyReferer=https:%2F%2Fwww.google.com%2F)
[DevBytes: Google Fit APIs for Android - Setup and Sensors](https://youtu.be/jwaQaWGLlTo)
[DevBytes: Google Fit APIs for Android - Recording and History](https://youtu.be/hS8OLV-D1lw)

**Comment by DahamChoi** [comment]
In order to provide the "Silverwork" solution we designed, it is necessary to properly adjust and utilize the Google Fitness API. In addition, the Google Fitness API has its own Cloud Store, so it is necessary to minimize the risk of redundant data storage with the FireStore managed by Firebase.

theory)
1. Google Fitness API stores and manages my activities through subscription and unsubscription (Record API).
2. Through the Sesson API, the activity can be divided into zones.
3. Data saved through the Record API can be read using the History API. This is the start time and end time of the query that can be requested at this time.
3-1. When reading values ​​through the History API, only the session we created can be retrieved.

Hypothetical reasoning)
1. Mission end real time when the mission is over-Set the mission time as the start time and the real time as the end time to create and save a session.
2. Save the mission start time and end time in the FireStore.
3. In the Achievement-related part, using the start time and end time in FireStore, request a query to the History API to get the value.
